stages:
    - build
    - deploy

build:
    stage: build
    script:
        - npm install
        - npm install -g gulp
        - gulp build-ls
        - gulp build-main
    artifacts:
        paths:
            - _site/ls_vertretungsplan_me
            - _site/vertretungsplan_me
    cache:
        paths:
        - node_modules/

deploy:
    stage: deploy
    only:
        - master
    script:
        - scp -r -o UserKnownHostsFile=/keys/known_hosts -i /keys/id_rsa _site/ls_vertretungsplan_me/* gitlab-deploy-web@trelawney.rami.io:/var/www/web/ls/
        - scp -r -o UserKnownHostsFile=/keys/known_hosts -i /keys/id_rsa _site/vertretungsplan_me/* gitlab-deploy-web@trelawney.rami.io:/var/www/web/main/