stages:
    - build
    - deploy

build:
    stage: build
    script:
        - npm install
        - npm install -g gulp
        - gulp build-ls
        - gulp build-main
    artifacts:
        paths:
            - _site/ls_vertretungsplan_me
            - _site/vertretungsplan_me
            
deploy:
    stage: deploy
    only: production
    script:
        - scp -r -o UserKnownHostsFile=/keys/known_hosts -i /keys/vertretungsplan_deploy _site/ls_vertretungsplan_me/* tomcat@hamilton.rami.io:usr/share/nginx/www/web/ls/